version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

# workflows:
#   build_test_deploy:
#     jobs:
#       - build_test
#       - docker_hub_build_push_image:
#           requires:
#             - build_test
#       - aws-ecr/build_and_push_image:
#           region: us-east-1
#           account-url: ${AWS_ECR_URLL}
#           repo: ${CIRCLE_PROJECT_REPONAME}
#           tag: ${CIRCLE_BUILD_NUM}
#           requires:
#             - build_test
# jobs:
#   build_test:
#     docker:
#       - image: circleci/python:2.7.14
#     steps:
#       - checkout
#       - run:
#           name: Setup VirtualEnv
#           command: |
#             virtualenv helloworld
#             . helloworld/bin/activate
#             pip install --no-cache-dir -r requirements.txt
#       - run:
#           name: Run Tests
#           command: |
#             . helloworld/bin/activate
#             python test_hello_world.py
#   docker_hub_build_push_image:
#     docker:
#       - image: circleci/python:2.7.14
#     steps:
#       - checkout
#       - setup_remote_docker:
#           docker_layer_caching: false
#       - run:
#           name: Build and push Docker image to Docker Hub
#           command: |
#             echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> ${BASH_ENV}
#             echo 'export IMAGE_NAME=${CIRCLE_PROJECT_REPONAME}' >> ${BASH_ENV}
#             source ${BASH_ENV}
#             docker build -t ${DOCKER_LOGIN}/${IMAGE_NAME} -t ${DOCKER_LOGIN}/${IMAGE_NAME}:${TAG} .
#             echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
#             docker push ${DOCKER_LOGIN}/${IMAGE_NAME}


workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          # context: myContext
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ~
          profile-name: html
          region: AWS_REGION
          repo: myecrrepository
          skip-when-tags-exist: false
          tag: 'v1.0'