# version: 2.1

# orbs:
#   aws-ecr: circleci/aws-ecr@6.7.0
#   aws-eks: circleci/aws-eks@0.2.3

# workflows:
#   build_and_push_image:
#     jobs:
#       - aws-ecr/build-and-push-image:
#           account-url: AWS_ECR_ACCOUNT_URL
#           aws-access-key-id: AWS_ACCESS_KEY_ID
#           aws-secret-access-key: AWS_SECRET_ACCESS_KEY
#           create-repo: true
#           dockerfile: Dockerfile
#           path: .
#           region: AWS_REGION
#           repo: circleci-ecr-orb-demo
#           tag: "$CIRCLE_SHA1"

version: 2
jobs:
  test:
    docker:
      - image: openjdk:8
    steps:
      - checkout
      #- run: ./gradlew clean test --stacktrace --info
  deploy:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run: 
          name: Build image and push
          command: 
            chmod +x package.sh
            ./package.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main